### PR TITLE
fix: convert `crate`, `self`, and `super` references into absolute paths

### LINKED ISSUE #4: Resolve `crate`/`super`/`self` references inside quoted code
Right now, we have to resort to tricks like importing the current module under an aliased name.

### PR DESCRIPTION
**Pull request by shadaj**
Fixes #4

### CODE REVIEW

File: stageleft/src/rewrite_paths.rs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    pub(super) module_path: Option<Path>,
+}
+
+impl VisitMut for RewritePaths {
+    fn visit_path_mut(&mut self, path: &mut Path) {
+        if path
+            .segments
+            .first()
+            .map(|s| s.ident == "crate")
+            .unwrap_or(false)
```
Comment (MingweiSamuel) [inline stageleft/src/rewrite_paths.rs:14]: nit: `.is_some_and(|s| s.ident == "crate")`

File: stageleft/src/rewrite_paths.rs [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+                .iter()
+                .chain(path_tail)
+                .cloned()
+                .collect();
+        } else if let Some(module_path) = &self.module_path {
+            if path
+                .segments
+                .first()
+                .map(|s| s.ident == "self")
+                .unwrap_or(false)
```
Comment (MingweiSamuel) [inline stageleft/src/rewrite_paths.rs:29]: ^

File: stageleft/src/rewrite_paths.rs [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+                    .segments
+                    .iter()
+                    .chain(path_tail)
+                    .cloned()
+                    .collect();
+            } else if path
+                .segments
+                .first()
+                .map(|s| s.ident == "super")
+                .unwrap_or(false)
```
Comment (MingweiSamuel) [inline stageleft/src/rewrite_paths.rs:42]: ^

**Review by MingweiSamuel — APPROVED** [review]
`self::super::...` is a pathological case not handled, but also would be very unusual for a user to have

https://internals.rust-lang.org/t/use-self-super-is-accepted-is-this-intended/15616
